// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/OlegVanyaGreatBand/architecture-lab-3/server/models"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*TelemetryApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := models.NewStore(db)
	telemetryHttpHandler := models.HttpHandler(store)
	telemetryApiServer := &TelemetryApiServer{
		Port:             port,
		TelemetryHandler: telemetryHttpHandler,
	}
	return telemetryApiServer, nil
}
